apiVersion: apps/v1
kind: Deployment
metadata:
  name: promptic-frontend
  namespace: promptic-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promptic-frontend
  template:
    metadata:
      labels:
        app: promptic-frontend
    spec:
      containers:
        - name: promptic-frontend
          image: itzmohit96/promptic-frontend:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: promptic-frontend
  namespace: promptic-core
spec:
  type: ClusterIP
  selector:
    app: promptic-frontend
  ports:
    - port: 80
      targetPort: 80
